In [756]:
import seaborn as sns
import pandas as pd
import numpy as np

In [757]:
data =sns.load_dataset("flights")
data

year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [758]:
data.isnull().sum()

year          0
month         0
passengers    0
dtype: int64

In [759]:
data.columns

Index(['year', 'month', 'passengers'], dtype='object')

In [760]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
r=['year', 'month', 'passengers']
for i in r:
    data[i]=le.fit_transform(data[i])
data

year  month  passengers
0       0      4           1
1       0      3           4
2       0      7          10
3       0      0           9
4       0      8           6
..    ...    ...         ...
139    11      1         116
140    11     11         112
141    11     10         105
142    11      9          91
143    11      2         103

[144 rows x 3 columns]

In [761]:
x=data.drop('passengers',axis=1)
x

year  month
0       0      4
1       0      3
2       0      7
3       0      0
4       0      8
..    ...    ...
139    11      1
140    11     11
141    11     10
142    11      9
143    11      2

[144 rows x 2 columns]

In [762]:
y=data['passengers']
y

0        1
1        4
2       10
3        9
4        6
      ... 
139    116
140    112
141    105
142     91
143    103
Name: passengers, Length: 144, dtype: int64

In [763]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.35,random_state=2)

In [764]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(xtrain,ytrain)

RandomForestRegressor()

In [765]:
accuracy=(rf.score(xtest,ytest)*100)
accuracy

93.07079077715818

In [766]:
predict=(rf.score(xtrain,ytrain))*100
predict

98.64991258494614

In [767]:
w=[[11,10]]
w1=rf.predict(w)
w1

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([104.82])

In [768]:
from sklearn.svm import SVR
sv=SVR()
sv.fit(xtrain,ytrain)

SVR()

In [769]:
accuracy1=(sv.score(xtest,ytest))*100
accuracy1

50.02685161569674

In [770]:
predict1=(sv.score(xtrain,ytrain))*100
predict1

48.79727653301461

In [771]:
w2=[[0,7]]
wr=sv.predict(w2)
wr

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([39.92401075])

In [772]:
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor
fg=AdaBoostRegressor()
fg.fit(xtrain,ytrain)

AdaBoostRegressor()

In [773]:
from sklearn.metrics import accuracy_score

In [774]:
accur=(fg.score(xtest,ytest)*100)
accur

92.74897147760315

In [775]:
predi=(fg.score(xtrain,ytrain))*100
predi

92.71787645566073

In [776]:
w2l=[[11,10]]
wp=fg.predict(w2l)
wp

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(


array([99.25])

In [777]:
gj=GradientBoostingRegressor()
gj.fit(xtrain,ytrain)

GradientBoostingRegressor()

In [778]:
accr=(gj.score(xtest,ytest)*100)
accr

97.4694997177625

In [779]:
pred=(gj.score(xtrain,ytrain))*100
pred

99.60595674001262

In [780]:
wl=[[11,10]]
wz=fg.predict(wl)
wz

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(


array([99.25])

In [781]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=0)

In [782]:
from xgboost import XGBRegressor
xgb=XGBRegressor()
xgb.fit(xtrain,ytrain)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [783]:
acc=(xgb.score(xtest,ytest)*100)
acc

97.945025630595

In [784]:
prd=(xgb.score(xtrain,ytrain))*100
prd

99.9999690237776

In [785]:
pl=[[11,10]]
wi=xgb.predict(pl)
wi


array([104.99497], dtype=float32)